name: ci
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16, 18, 20 ]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: test
        run: pnpm i --no-frozen-lockfile && pnpm run test && pnpm run test:e2e

  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16, 18, 20 ]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependent
        run: pnpm i --no-frozen-lockfile

      - name: run test cov
        run: pnpm run test:cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
